services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    # Usa o Dockerfile no diretório atual para construir a imagem
    build: .
    container_name: my-library-app-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/my-library-db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod
volumes:
  mongo_data: