apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dsangelo/my-library-app:v1
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: HOST
              value: "0.0.0.0"
            - name: DATABASE_URL
              value: mongodb://mongodb-service:27017/my-library-db
