apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000       # Porta do cluster
      targetPort: 3000 # Porta do container
      nodePort: 30001  # Porta externa (NodePort exposto)
